### PR TITLE
Added Text Input Group

### PR DESCRIPTION
**Pull request by okolomiets**

### CODE REVIEW

**Comment by kurpav** [comment]
I think this component should be reusable, so I imagine it like this:
```
<div class="dd__control">
  <i class="dd__icon"></i>
  <input>
  <button>
  <button>
</div>
```
What do you think?

**Comment by okolomiets** [comment]
well, my point is to re-use all existing dd-ui inputs/buttons within the 'group'.
also, there are few use cases where we need to customize inner elements independently on 'group' items.

**Comment by kurpav** [comment]
I think it's too complicated now

**Comment by okolomiets** [comment]
I think the main purpose of 'input group' is to organize elements into 'side-by-side' row and fix borders/radiuses if any exist. And that's it. Then if we need to create UI element as grouped items, e.g. 'poll option' we just add another class to describe it. See example in this PR.

**Comment by okolomiets** [comment]
Here is a demo where 'group' of dd-ui elements (_**input with icon and text limit**_ and _**default button with icon**_) organized into Poll option with form validation error message.


Another use case: draggable items in ui-tree

**Comment by okolomiets** [comment]
I added UI element: **List Filter**, as yet another example illustrated my idea. It consists of existing dd-ui buttons. The group wrapper also has class `dd__filter__list` to describe the group. 

```
<div class="dd__splitted-group dd__list__filter">
      <button class="btn btn--default btn--xs dd__splitted-item">All</button>
      <button class="btn btn--default btn--xs dd__splitted-item active">Unarchived</button>
      <button class="btn btn--default btn--xs dd__splitted-item">Archived</button>
</div>
```

**Pull request merged**
